language: generic

addons:
  apt:
    packages:
    - python3

before_script:
  - pip install --upgrade pip
  - pip install -I numpy==1.8.2
  - pip3 install -I numpy==1.8.2

script:
- python  -m compileall -f arc/*.py
- python3 -m compileall -f arc/*.py
- python arc/setupc.py build_ext --inplace
- python3 arc/setupc.py build_ext --inplace
