language: generic
env:
  global:
    - TWINE_USERNAME=nikolasibalic
matrix:
    include:
        - os: linux
          sudo: required
          env: TOXENV=py27
        - os: linux
          sudo: required
          env: TOXENV=py3
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py3
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$TOXENV" == "py27" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
    else
      if [[ "$TOXENV" == "py27" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    fi

  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH

script:
- conda update -n base --yes conda
- conda install --yes numpy
- conda install --yes scipy
- conda install --yes wheel
- python  -m compileall -f arc/*.py
- python setup.py build
- rm -rf build
- |
    if [[ $TRAVIS_TAG ]]; then
      conda install --yes twine;
      python setup.py sdist bdist_wheel;
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*.whl;
      fi;
    fi
