language: generic

addons:
  apt:
    packages:
    - python3

script:
- python  -m compileall -f arc/*.py
- python3 -m compileall -f arc/*.py
- gcc -Wall -Wextra -pedantic -std=c99 -O3 arc/nvwcpp.c -lm
