language: generic

addons:
  apt:
    packages:
    - python3

script:
- python  -m compileall -f arc/*.py
- python3 -m compileall -f arc/*.py
- python arc/setupc.py build_ext --inplace
- python3 arc/setupc.py build_ext --inplace
